#!/bin/bash
set -e

# Generates the runtime VerneMQ config (vernemq-local.conf) consumed by
# setup_mqtt.sh and edited at runtime by system_server's mqtt_routes.py.
#
# The generated file is gitignored because it carries the bridge credential.
# Static config (listener, webhooks, topic map, TLS) is baked in here; only the
# bridge identity is parameterized.
#
# Usage:
#   BRIDGE_PASSWORD=secret ./build.sh
#   BRIDGE_ADDRESS=mqtt.flexiblevision.com:443 BRIDGE_PASSWORD=secret ./build.sh
#
# Inputs (environment variables):
#   BRIDGE_ADDRESS    bridge endpoint host:port   (default: mqtt-dev.flexiblevision.com:443)
#   BRIDGE_USERNAME   bridge username             (default: bridge)
#   BRIDGE_CLIENT_ID  bridge client id            (default: local-bridge)
#   BRIDGE_PASSWORD   bridge password/token       (required unless --allow-placeholder)
#
# Flags:
#   --allow-placeholder   write a placeholder password instead of failing
#                         (useful for first-time scaffolding; the real value is
#                         injected later by mqtt_routes.py on token refresh)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# Output path — overridable so setup_mqtt.sh can keep both in sync.
CONFIG_FILE="${CONFIG_FILE:-$SCRIPT_DIR/vernemq-local.conf}"

ALLOW_PLACEHOLDER=0
for arg in "$@"; do
    case "$arg" in
        --allow-placeholder) ALLOW_PLACEHOLDER=1 ;;
    esac
done

# Bridge identity — overridable via environment, with sane defaults.
BRIDGE_ADDRESS="${BRIDGE_ADDRESS:-mqtt-dev.flexiblevision.com:443}"
BRIDGE_USERNAME="${BRIDGE_USERNAME:-bridge}"
BRIDGE_CLIENT_ID="${BRIDGE_CLIENT_ID:-local-bridge}"

if [ -z "${BRIDGE_PASSWORD:-}" ]; then
    if [ "$ALLOW_PLACEHOLDER" -eq 1 ]; then
        BRIDGE_PASSWORD="your-bridge-secret"
        echo "WARNING: BRIDGE_PASSWORD not set — writing placeholder."
        echo "         The bridge will not authenticate until a real token is written"
        echo "         (set BRIDGE_PASSWORD and re-run, or let system_server inject it)."
    else
        echo "ERROR: BRIDGE_PASSWORD is not set."
        echo "Set it before running:  BRIDGE_PASSWORD=<token> $0"
        echo "Or scaffold a placeholder:  $0 --allow-placeholder"
        exit 1
    fi
fi

echo "Generating VerneMQ config..."
echo "  Output:   $CONFIG_FILE"
echo "  Endpoint: $BRIDGE_ADDRESS"
echo "  Username: $BRIDGE_USERNAME"
echo "  ClientID: $BRIDGE_CLIENT_ID"
echo "  Password: $(printf '%s' "$BRIDGE_PASSWORD" | cut -c1-2)***"

cat > "$CONFIG_FILE" <<EOF
## Basic listener config
listener.tcp.default = 0.0.0.0:1883
allow_anonymous = off

## Webhook plugin configuration
plugins.vmq_webhooks = on

vmq_webhooks.mywebhook1.hook = auth_on_register
vmq_webhooks.mywebhook1.endpoint = http://172.17.0.1:5000/api/capture/mqtt/auth

vmq_webhooks.mywebhook2.hook = auth_on_subscribe
vmq_webhooks.mywebhook2.endpoint = http://172.17.0.1:5000/api/capture/mqtt/subscribe

vmq_webhooks.mywebhook3.hook = auth_on_publish
vmq_webhooks.mywebhook3.endpoint = http://172.17.0.1:5000/api/capture/mqtt/publish

## Bridge to GKE VerneMQ
## Generated by build.sh — edit BRIDGE_* env vars and re-run rather than hand-editing.
plugins.vmq_bridge = on

vmq_bridge.ssl.gke = ${BRIDGE_ADDRESS}
vmq_bridge.ssl.gke.client_id = ${BRIDGE_CLIENT_ID}
vmq_bridge.ssl.gke.username = ${BRIDGE_USERNAME}
vmq_bridge.ssl.gke.password = ${BRIDGE_PASSWORD}
vmq_bridge.ssl.gke.insecure = on
vmq_bridge.ssl.gke.tls_version = tlsv1.2
vmq_bridge.ssl.gke.cleansession = on


## Outbound: device → cloud
## NOTE: VerneMQ cuttlefish parser strips '#' from bridge topics.
## Use explicit subtopic patterns instead of '#' wildcards.
vmq_bridge.ssl.gke.topic.1 = devices/+/system/sync out 0
vmq_bridge.ssl.gke.topic.2 = devices/+/assembly/+/started out 0
vmq_bridge.ssl.gke.topic.3 = devices/+/assembly/+/workstation/started out 0
vmq_bridge.ssl.gke.topic.4 = devices/+/assembly/+/workstation/completed out 0
vmq_bridge.ssl.gke.topic.5 = devices/+/assembly/+/workstation/skipped out 0
vmq_bridge.ssl.gke.topic.6 = devices/+/assembly/+/step/recorded out 0
vmq_bridge.ssl.gke.topic.7 = devices/+/assembly/+/status out 0
vmq_bridge.ssl.gke.topic.8 = devices/+/assembly/+/line/transition out 0
vmq_bridge.ssl.gke.topic.9 = devices/+/assembly/+/logs out 0
vmq_bridge.ssl.gke.topic.10 = devices/+/assembly/+/metrics out 0
vmq_bridge.ssl.gke.topic.11 = devices/+/stats/+ out 0
vmq_bridge.ssl.gke.topic.12 = devices/+/heartbeat out 0

## Inbound: cloud → device (commands)
vmq_bridge.ssl.gke.topic.13 = devices/+/system/reboot in 0
vmq_bridge.ssl.gke.topic.14 = devices/+/system/shutdown in 0
vmq_bridge.ssl.gke.topic.15 = devices/+/system/refresh_backend in 0
vmq_bridge.ssl.gke.topic.16 = devices/+/system/node_trigger in 0
vmq_bridge.ssl.gke.topic.17 = devices/+/system/toggle_sync in 0
vmq_bridge.ssl.gke.topic.18 = devices/+/system/update_software in 0
vmq_bridge.ssl.gke.topic.19 = devices/+/system/start_teamviewer in 0
vmq_bridge.ssl.gke.topic.20 = devices/+/models in 0
vmq_bridge.ssl.gke.topic.21 = devices/+/preset/+ in 0
vmq_bridge.ssl.gke.topic.22 = devices/+/timemachine/+ in 0
EOF

chmod 600 "$CONFIG_FILE"

echo "Done. Wrote $(wc -l < "$CONFIG_FILE") lines to $CONFIG_FILE"
echo "Next: run ./setup_mqtt.sh to (re)start the broker with this config."
